# Generated by Django 6.0.7 on 2026-07-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('company', 'name')},
        ),
        migrations.AddField(
            model_name='family',
            name='code',
            field=models.CharField(blank=True, help_text='Code unique de la famille', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familyattribute',
            name='validation_rules',
            field=models.JSONField(blank=True, help_text='Custom validation rules like min/max length, regex, etc.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('company', 'code'), ('company', 'name')},
        ),
    ]
