# Generated by Django 6.0.7 on 2026-07-20 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_family_unique_together_family_code_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyattribute',
            old_name='label',
            new_name='name',
        ),
        migrations.AlterUniqueTogether(
            name='family',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='immobilisation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, help_text="Code unique de l'entité", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='familyattribute',
            name='code',
            field=models.CharField(blank=True, help_text="Code unique de l'entité", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familyattribute',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entities', to='users.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='immobilisation',
            name='code',
            field=models.CharField(blank=True, help_text="Code unique de l'entité", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='code',
            field=models.CharField(blank=True, help_text="Code unique de l'entité", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='supplier',
            name='code',
            field=models.CharField(blank=True, help_text="Code unique de l'entité", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entities', to='users.company'),
        ),
        migrations.AlterField(
            model_name='family',
            name='code',
            field=models.CharField(blank=True, help_text="Code unique de l'entité", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entities', to='users.company'),
        ),
        migrations.AlterField(
            model_name='family',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='familyattribute',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entities', to='users.company'),
        ),
        migrations.AlterField(
            model_name='immobilisation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé'), ('CANCELLED', 'Annulé')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='site',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entities', to='users.company'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entities', to='users.company'),
        ),
        migrations.RemoveField(
            model_name='immobilisation',
            name='inventory_number',
        ),
    ]
