# Generated by Django 6.0.7 on 2026-07-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_rename_label_familyattribute_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyattribute',
            old_name='name',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='familyattribute',
            name='code',
        ),
        migrations.RemoveField(
            model_name='familyattribute',
            name='company',
        ),
        migrations.RemoveField(
            model_name='familyattribute',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='familyattribute',
            name='status',
        ),
        migrations.RemoveField(
            model_name='familyattribute',
            name='updated_by',
        ),
    ]
