# Generated by Django 6.0.7 on 2026-07-20 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_rename_name_familyattribute_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyattribute',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=20),
        ),
    ]
